on:
  workflow_dispatch:
    inputs:
      pass-unit-tests:
        description: Whether unit test should pass or not
        required: false
        default: true

jobs:
  lint-build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint and build
        run: echo "Linting and building project"
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Running unit tests
        run: echo "Running unit tests"
      - name: Pass or fail unit tests
        if: ${{ !inputs.pass-unit-tests }}
        run: exit 1
  deploy-nonprod:
    runs-on: ubuntu-latest
    needs:
      - lint-build
      - unit-tests
    steps:
      - name: Deploy to non-production
        run: echo "Deploying to non-production"
  e2e-tests:
    runs-on: ubuntu-latest
    needs:
      - deploy-nonprod
    steps:
      - name: Running end-to-end tests
        run: echo "Running end-to-end tests"
  deploy-prod:
    needs:
      - deploy-nonprod
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        run: echo "Deploying to production"
